# Generated by Django 5.0.6 on 2024-07-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_rename_title_prompt_navn_rename_text_prompt_tekst_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fileslistbox",
                    models.CharField(
                        choices=[("fil1", "filnavn1"), ("fil2", "filnavn")],
                        default="filnavn1",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
