# Generated by Django 5.0.6 on 2024-08-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_filelist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=2000)),
            ],
        ),
    ]
